### ISSUE TITLE
查看例子过程中随机会出现一个渲染错误

### ISSUE THREAD

**Issue by gisergao** [marsgis/mars3d#4]
![image](https://user-images.githubusercontent.com/29887283/134443316-08549b62-fddb-4f52-891e-326346f148a8.png)
WebGL发生渲染错误,渲染已经停止,请刷新页面。
TypeError: Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.

TypeError: Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.
    at createAndLinkProgram (http://127.0.0.1:8080/lib/Cesium/Cesium.js:1:966425)
    at reinitialize (http://127.0.0.1:8080/lib/Cesium/Cesium.js:1:969903)
    at initialize$b (http://127.0.0.1:8080/lib/Cesium/Cesium.js:1:969835)
    at ShaderProgram._bind (http://127.0.0.1:8080/lib/Cesium/Cesium.js:1:973648)
    at beginDraw (http://127.0.0.1:8080/lib/Cesium/Cesium.js:1:2592249)
    at Context.draw (http://127.0.0.1:8080/lib/Cesium/Cesium.js:1:2593798)
    at DrawCommand.execute (http://127.0.0.1:8080/lib/Cesium/Cesium.js:1:930877)
    at ComputeEngine.execute (http://127.0.0.1:8080/lib/Cesium/Cesium.js:1:2560769)
    at ComputeCommand.execute (http://127.0.0.1:8080/lib/Cesium/Cesium.js:1:1506762)
    at executeComputeCommands (http://127.0.0.1:8080/lib/Cesium/Cesium.js:1:3317680)

**Comment by muyao1987** [comment]
是否本地显卡比较差呢？或者使用最新版本浏览器查看，更多请参考教程：http://mars3d.cn/dev/guide/start/env.html

**Comment by gisergao** [comment]
测试了，使用的4GB显存的显卡，当使用超过90%时就会报错






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "marsgis/mars3d"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月23日(星期四) 上午10:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [marsgis/mars3d] 查看例子过程中随机会出现一个渲染错误 (#4)





 
是否本地显卡比较差呢？或者使用最新版本浏览器查看，更多请参考教程：http://mars3d.cn/dev/guide/start/env.html
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by muyao1987** [comment]
是否有大模型呢，可以参考这个教程看看 http://mars3d.cn/dev/guide/issue/webgl.html 
或者加我们微信群进行技术交流 http://mars3d.cn/community

**Comment by muyao1987** [comment]
是否有大模型呢，可以参考这个教程看看 http://mars3d.cn/dev/guide/issue/webgl.html 
或者加我们微信群进行技术交流 http://mars3d.cn/community
